name: tests-release
on:
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
      - run: npx twitter-snap@latest --help
      - run: npx twitter-snap@latest -o temp/{id}.png 1349129669258448897
      - run: npx twitter-snap@latest -o temp/{id}.mp4 1768794901586804837
